name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    name: Test Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1.6.0
        with:
          version: 1.5.3 
          arch: x86
          show-versioninfo: true 
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x86
          show-versioninfo: true 
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}

      