name: Register Package
on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: Version to register or component to bump
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Register Julia Package
        uses: julia-actions/RegisterAction@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
