name: TagBot
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 * * * *
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    #if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Julia TagBot
        uses: JuliaRegistries/TagBot@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
